# -*- coding: utf-8 -*-
"""Brain_Tumor_IMD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yxf1mzlyU6sim2Ga5meINCFerFgok_v8
"""

import tensorflow as tf
from keras.src.legacy.saving import legacy_h5_format

# Step 1: Load the old or incompatible model safely
try:
    print("🔄 Trying to load model using modern loader...")
    model = tf.keras.models.load_model("model.h5", compile=False)
    print("✅ Loaded with modern loader")
except Exception as e:
    print(f"⚠️ Modern load failed: {e}")
    print("➡️ Trying legacy loader...")
    model = legacy_h5_format.load_model_from_hdf5("model.h5")
    print("✅ Loaded using legacy loader")

# Step 2: Rebuild the model cleanly layer-by-layer
print("\n🧩 Rebuilding model to fix Flatten input issue...")
new_model = tf.keras.Sequential()

for layer in model.layers:
    new_model.add(layer)

print("✅ Layers rebuilt successfully.")

# Step 3: Save the new clean model
new_model.save("fixed_model.h5")
print("\n💾 Model saved as 'fixed_model.h5'")
print("✅ You can now safely load this in your Streamlit app using:")
print("   model = tf.keras.models.load_model('fixed_model.h5', compile=False)")
